### ISSUE TITLE
Some wrong in Vector2 class

### ISSUE THREAD

**Issue by lizhijian-cn** [henry1123/gameobjectsForPython3#1]
1, the \_\_nonzero__ and \_\_div__ method may be changed to \_\_bool__ and \_\_truediv__
2, lose '_' in \_\_isub__ method

**Comment by henry1123** [comment]
Thanks for your suggestion. 
I have fixed the vector2 & vector3 bugs that related to __nonzero__, __div__, __isub__ . 
and add some test in the py files.
